name: Build and Deploy to GitHub Pages
jobs:
  build-and-deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build and deploy
        run: npm run deploy
